# Generated by Django 6.1.1 on 2026-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IniciativaESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Verdigis')),
                ('pilar', models.CharField(choices=[('E', 'Environmental (Ambiental)'), ('S', 'Social (Social)'), ('G', 'Governance (Governança)')], max_length=1, verbose_name='Pilar ESG')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('meta_impacto', models.CharField(max_length=255, verbose_name='Meta de Impacto')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iniciativa ESG',
                'verbose_name_plural': 'Iniciativas ESG',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('bio', models.TextField(verbose_name='Minibio')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil LinkedIn')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=150, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
            },
        ),
    ]
